const filterTypes = {
  SET_TEXT_FILTER: 'SET_TEXT_FILTER',
  SET_MAX_PRICE_FILTER: 'SET_MAX_PRICE_FILTER',
  SET_MIN_PRICE_FILTER: 'SET_MIN_PRICE_FILTER',
  RESET_FILTER: 'RESET_FILTER',
  APPLY_FILTER: 'APPLY_FILTER',
  CLEAR_RECENT_SEARCH: 'CLEAR_RECENT_SEARCH',
  REMOVE_SELECTED_RECENT: 'REMOVE_SELECTED_RECENT',
};

export default filterTypes;
