const cartTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  REDUCE_CART_ITEM: 'REDUCE_CART_ITEM',
};

export default cartTypes;
