const blogTypes = {
  ADD_BLOG_START: 'ADD_BLOG_START',
  ADD_BLOG_SUCCESS: 'ADD_BLOG_SUCCESS',
  ADD_BLOG_ERROR: 'ADD_BLOG_ERROR',

  BLOG_RESET: 'BLOG_RESET',

  FETCH_BLOGS_START: 'FETCH_BLOGS_START',
  FETCH_BLOG_START: 'FETCH_BLOG_START',

  SET_BLOGS: 'SET_BLOGS',
  SET_BLOG: 'SET_BLOG',

  DELETE_BLOG_START: 'DELETE_BLOG_START',
  DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
  DELETE_BLOG_ERROR: 'DELETE_BLOG_ERROR',
};

export default blogTypes;
